### PR TITLE
SUITEDEV-23229 - add TranslateModule as generic type

### PR DESCRIPTION
**Pull request by ejwalker**
A generic type needs to be added to the `ModuleWithProviders` which is blocking Angular 10 update in the me-ui  ([SUITEDEV-23229](https://emarsys.jira.com/browse/SUITEDEV-23229)).

API info on the Angular docs at https://angular.io/api/core/ModuleWithProviders

### CODE REVIEW

**Comment by ejwalker** [comment]
@Valetudox @blacksonic @emartech/me-content  can you please review this PR (I cannot assign reviewers)

**Comment by rudywaltz** [comment]
Hi @ejwalker,
Can you fix the peer dependency as well?
https://github.com/emartech/angular-translate/blob/master/package.json#L37

**Comment by ejwalker** [comment]
> Hi @ejwalker,
> Can you fix the peer dependency as well?
> https://github.com/emartech/angular-translate/blob/master/package.json#L37

Hi @rudywaltz, assuming since that only affects turning Ivy on in the `me-ui`. it will be done in this separate ticket [SUITEDEV-23153](https://emarsys.jira.com/browse/SUITEDEV-23153)

**Comment by rudywaltz** [comment]
> > Hi @ejwalker,
> > Can you fix the peer dependency as well?
> > https://github.com/emartech/angular-translate/blob/master/package.json#L37
> 
> Hi @rudywaltz, assuming since that only affects turning Ivy on in the `me-ui`. it will be done in this separate ticket [SUITEDEV-23153](https://emarsys.jira.com/browse/SUITEDEV-23153)

My problem here you would like fix because of angular 10 upgrades, but the peerDependecy says this is not compatible higher then 8. so It throws a warning when you install, it's not harmful but not too nice, and we see it's compatible (just not support Ivy), so you can use 
`>=8.0.0` instead of  `"@angular/core": "^8.0.0"`

Screenshot 2020-07-03 16 13 17

**Pull request merged**
